### PR TITLE
Vim/Neovim using vim-flow and install eslint globally

### LINKED ISSUE #13: Issue when saving .js files
Was previously a neovim user using Vundle for plugin management, ran the curl command in the readme and got this when trying to save a `.js` file. This doesn't seem to happen on other filetypes.
## Screenshot:

screen shot 2016-09-21 at 9 03 38 am

### PR DESCRIPTION
**Pull request by renatoagds**
**CHANGE LOG**

Moving `vim-flow` to be installed in vim and neovim, since we're using neomake with it too.
Install `eslint` with `syntastic` and `neomake` (this one fix #13)

### CODE REVIEW

**Comment by eanplatter** [comment]
Hey @renatoagds I attempted to do a fresh install with your fork and it didn't seem to globally install eslint on my machine. I don't know how vim scripts work, but would it make sense to have the install.sh script run the install?

I'm also not so sure how I feel about having something else globally install node modules on my machine, I've always felt that was a little hard to swallow, @zperrault maybe it would make sense to just update the README to let people know they need eslint? Not sure which solution is the best. ¯_(ツ)_/¯

**Comment by sloanelybutsurely** [comment]
@renatoagds First of all, thank you for opening this PR!

@eanplatter @renatoagds 🤔 Right now the project installs `tern` globally. I feel like if don't want to install `eslint` and `flow-bin` globally then we should remove that and add add `tern` to the list of prereqs in the `README`.

Do the atom plugins work without installing things globally?

More: The flow stuff _should_ work with the project's local copy of flow. We probably want to do the same for all of this.

**Comment by eanplatter** [comment]
Yeah I think keeping things as close to atom would be good. Auto installing global deps seems really heavy handed. I'd say the eslint stuff should work from the users project config. I'll try to do some more debugging on it later tonight.

**Comment by renatoagds** [comment]
@eanplatter about the eslint, we have few plugins that search for local eslint instead global:

https://github.com/benjie/neomake-local-eslint.vim
https://github.com/mtscout6/syntastic-local-eslint.vim

But it's not the default for Neomake and Syntastic.

IMO, any of the ways that we follow will be good.

**Comment by sloanelybutsurely** [comment]
I'm leaning more towards adopting ale and getting rid of neomake. I'd like to avoid having to install things globally. I want these features to work if eslint or flow are being used locally--not globally.

**Pull request closed without merging**
